# Galaktia Application Context

# Server components
server:
  server:
    path: galaktia.model.standalone:WebSocketServer
    constructor-args:
      0: config:server::bind-address
      1: object:request-handler-factory
  request-handler-factory:
    path: galaktia.model.base:make_request_handler_factory
    constructor-args:
      codec: object:codec
      controller: object:controller
      session_dao: object:session-dao
  codec:
    path: galaktia.model.codec:JsonCodec
  controller:
    path: galaktia.model.dispatcher:DispatcherController
    constructor-args:
      dao: object:persistence::dao
  session-dao:
    path: galaktia.model.base:SessionDAO

# Persistence (data access layer) components
persistence:
  dao:
    path: galaktia.persistence.dao:DAOLocator
    constructor-args:
      session: object:persistence::session
  engine:
    type: factory
    path: sqlalchemy:create_engine
    constructor-args:
      0: config:persistence::database-url
  sessionmaker:
    type: factory
    path: sqlalchemy.orm:sessionmaker
    constructor-args:
      bind: object:engine
      autocommit: config:persistence::autocommit
      autoflush: config:persistence::autoflush
  session:
    type: factory
    path: sqlalchemy.orm:scoped_session
    constructor-args:
      0: object:sessionmaker

