server:
  server:
    path: galaktia.model.base:BaseServer
    constructor-args:
      codec: object:codec
      controller: object:controller
  codec:
    path: galaktia.model.codec:JsonCodec
  controller:
    path: galaktia.model.dispatcher:DispatcherController
    constructor-args:
      dao: object:persistence::dao

persistence:
  dao:
    path: galaktia.persistence.dao:DAOLocator
    constructor-args:
      session: object:persistence::session
  engine:
    type: factory
    path: sqlalchemy:create_engine
    constructor-args:
      0: config:persistence::database-url
  sessionmaker:
    type: factory
    path: sqlalchemy.orm:sessionmaker
    constructor-args:
      bind: object:engine
      autocommit: config:persistence::autocommit
      autoflush: config:persistence::autoflush
  session:
    type: factory
    path: sqlalchemy.orm:scoped_session
    constructor-args:
      0: object:sessionmaker

