# Google App Engine application configuration file

application: galaktia-web
version: 1
runtime: python
api_version: 1

handlers:

# *************
# STATIC FILES
# *************

# - url: /robots.txt
#   static_files: static/text/robots.txt
#   upload: static/text/robots.txt
# 
- url: /favicon.ico
  static_files: assets/images/favicon.ico
  upload: assets/images/favicon.ico

# *************
#  STATIC DIRS
# *************

- url: /images
  static_dir: assets/images

- url: /css
  static_dir: assets/css

- url: /js
  static_dir: assets/js

- url: /flash
  static_dir: assets/flash


# ***********************
#  FRONTEND CONTROLLERS
# ***********************

- url: /.*
  script: controller/main.py

# - url: /otraurl
#   script: otro_controller.py

